# Generated by Django 4.2.7 on 2023-11-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_alter_livros_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
